### ISSUE TITLE
[pipelines] Escrever tutorial de como rodar localmente e subir uma captura

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/pipelines#1]
- [ ] testar @lucascr91 @vncsna

**Comment by fernandascovino** [comment]
acho legal esclarecer no `readme`: 

## Estrutura do repositório
- o que é projeto X base, vi que a estrutura é meio duplicada entre ambos
- listar a estrutura tipo em [`project-templates`](https://github.com/JoaoCarabetta/project-templates/tree/master/basic#project-organization) para ficar claro onde adicionar uma captura

## Desenvolvimento

### Configuração
- requisitos, etc

### Subindo uma captura (bases)
- CLI: `python manage.py add_dataset` parece um comando bem útil de adicionar... pelo que vi, seria igual ao `add_project` mas dentro de `bases` e sem add um agent
- tem como add uma captura somente pela UI? seria legal colocar aqui

### Como subir um novo projeto
- podem existir outros projetos além de `bases`?

## Produção 

### Configuração
- requisitos, etc

### Subindo pipeline em produção
...

### Acessando a UI do Prefect
...
