### ISSUE TITLE
[fix] Imputar timezone brasileira na task de update_metadata para todos os flows

### ISSUE THREAD

**Issue by lucascr91** [basedosdados/pipelines#128]
Em todos os flows, a task `update_metadata` atualiza ao menos o campo `last_updated: data`, ver abaixo:

```python
update_metadata(
    dataset_id=dataset_id,
    table_id=table_id,
    fields_to_update=[
        {"last_updated": {"data": datetime.now().strftime("%Y-%m-%d %H:%M:%S")}},
        {"temporal_coverage": [temporal_coverage]},
    ],
    upstream_tasks=[temporal_coverage],
)
```
No entanto, dessa forma o metadado está utilizando o tempo da máquina em que o cluste do k8 roda. Como essa informação é consumida pelo botdosdados, então, idealmente, ela deveria registrar a hora no Brasil.

**Comment by laura-l-amaral** [comment]
Issue não faz mais sentido já que reformularmos toda task de update_metadata
