### ISSUE TITLE
[infra] Implementar pipeline para dados da ANP (preços de combustíveis)

### ISSUE THREAD

**Issue by lucascr91** [basedosdados/pipelines#150]
# O processo de atualização

A ANP, conforme a [página oficial](https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/serie-historica-de-precos-de-combustiveis) e os [metadados,](https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/shpc/metadados-serie-historica-precos-combustiveis-1.pdf) faz uma pesquisa semanal de preço em 459 localidades do país (listados na [metodologia de coleta](https://www.gov.br/anp/pt-br/assuntos/precos-e-defesa-da-concorrencia/precos/precos-revenda-e-de-distribuicao-combustiveis/arquivos-metodologia/metodologia-coleta.pdf) e publica os resultados semanalmente, fazendo, posteriormente, agregações mensais e semestrais. Os dados trazem a informação da revendedora (com informações de região, uf, município, CNPJ, endereço completo, CEP), bem como o dia da coleta e demais informações relevantes, como a bandeira do posto, o produto, valores e a unidade de medida.

Deve-se observar, ainda, que as agregações são feitas de forma diferentes, conforme abaixo

1. **Séries históricas de anos anteriores ao corrente**: todos os produtos e distribuidoras em arquivos semestrais (iniciando em 2004/S1). Obs: o diesel S-500 só pode ser usado em motores fabricados até 2012, o S-10 irá substituí-lo. A ANP optou por diferenciar o S-10 dos demais tipos com as nomenclaturas “diesel s10” e “diesel”.
2. **Agrupamento do ano corrente**: os dados são agrupados por mês, porém os dados aqui são fornecidos em 3 arquivos diferentes, agrupados por produto, da seguinte forma:
    1. Óleo diesel (S-10 e S-500) + GNV
    2. Etanol hidratado + Gasolina C
    3. GLP P13 (gás de cozinha em botijões de 13kg)
3. **Quatro últimas semanas**: seguem a mesma divisão de arquivos anteriores, sendo que, a cada semana, a primeira é eliminada e incluída a nova

# Nível de observação

Conclui-se, então, que o nível de observação dos dados é dia da coleta, posto e produto. Um posto é observado uma vez por semana, mas em um dia específico desta. Não existe um identificador de semana, mas de dia. Assim, caberia a quem estivesse analisando os dados fazer o agrupamento por semana, caso esta seja a granularidade desejada. Temos que ter cuidado com a falta de uniformidade na contagem do tempo, uma vez que os meses possuem número de semanas diferentes (entre 4 e 4,2857 semanas) 

# Modelo ideal de pipeline

A pipeline rodaria diariamente para verificar se houve alguma atualização (se ela rodar semanalmente perderá eventuais atrasos na divulgação dos dados). Como as datas não são identificadas externamente, seria necessário baixar os arquivos e verificar se a data mais recente é posterior à última data que foi coletada. Os dados das últimas 4 semana contém dados das 3 semanas anteriores, que já estão no banco.

- Em caso negativo, a pipeline para
- Em caso positivo, os dados constantes do arquivo baixado devem ser filtrados (apenas os dados mais recentes), concatenados aos dados atuais no GCS e ser feita a materialização incremental, uma vez que os dados são muito grandes para materializar com toda a carga inicial

# Particionamento e clusterização

O melhor particionamento seria pela data de coleta (ver a [documentação da Google](https://cloud.google.com/bigquery/docs/partitioned-tables#date_timestamp_partitioned_tables)), com granularidade [diária ou mensal](https://cloud.google.com/bigquery/docs/partitioned-tables#select_daily_hourly_monthly_or_yearly_partitioning). Observar os [limites do BigQuery](https://cloud.google.com/bigquery/quotas#partitioned_tables)

Para os clusters, pode-se usar o seguinte:

- produto
- estado

# Falhas

Como os dados são atualizados constantemente e não persistem na fonte (o arquivo semanal é substituído), precisamos considerar as seguintes falhas:

- Problemas técnicos que impedem a pipeline de rodar por mais de uma semana
- Falta de atualização por parte da ANP
- Finais de semana, feriados e recessos

O processo descrito acima permite que uma pipeline possa ser executada sem perda até 3 semanas após a data esperada, uma vez que ao longo desse tempo ainda teríamos os dados nos arquivos semanais. Em caso de uma falha maior, seria necessário atualizar os dados com as séries mensais (não agrupadas por semana, mas com a granularidade diária).

por @mfagundes

**Comment by laura-l-amaral** [comment]
#411
