### ISSUE TITLE
[infra] Implementar pipeline br_tse_eleicoes

### ISSUE THREAD

**Issue by lucascr91** [basedosdados/pipelines#188]
- [x] Implementar algoritmo que constrói `id_candidato_bd` em python
- [x] definir padrão de nomes de novas variáveis
- [x] editar os metadados e as tabelas em produção para incluir novas variáveis
- [x] criar pipeline para base desde 1998

**Comment by crislanealves** [comment]
>  criar pipeline para base desde 1998

Acho que essa é a minha `issue` preferida. <3
