### ISSUE TITLE
[DashBoard] Centralizar dashboards de acompanhamento de KPIs da BD

### ISSUE THREAD

**Issue by d116626** [basedosdados/pipelines#203]
Desenvolver/Adaptar os seguintes dashboards:

- [ ] Custos GCP: https://datastudio.google.com/u/0/reporting/24db7a11-a8e5-4160-9017-5b2b40eaa1fd
- [ ] Receita/Despesa da BD: https://basedosdados.org/transparencia
- [ ] KPIs e metricas de acesso: https://datastudio.google.com/u/0/reporting/1d3bdc87-6829-4177-bd15-f6a6694e9470/page/iR3yB
- [ ] Acessos do twitter: https://console.cloud.google.com/bigquery?project=basedosdados-dev&ws=!1m5!1m4!4m3!1sbasedosdados-dev!2sbr_bd_indicadores!3stwitter_metrics
- [x] Qualidade de dados (atualização, fontes quebradas, etc)

**Comment by rdahis** [comment]
Implementei pipelines para metadados em #221.

**Comment by laura-l-amaral** [comment]
na parte de dados tá duplicada com basedosdados/pipelines#616

posso fechar essa aqui e abrimos outra pra parte de Receitas e Despesas?
 @rdahis

**Comment by rdahis** [comment]
Pode. Isso era uma tarefa do @d116626 lá atrás que ficou aberta.
