### ISSUE TITLE
[infra] Container sendo desativado no flow de br_me_comex_stat.municipio_exportacao 

### ISSUE THREAD

**Issue by lucascr91** [basedosdados/pipelines#215]
Mensagem de erro:

```bash
Pod prefect-job-5b227a91-5p7j6 failed.
	Container 'flow' state: terminated
		Exit Code:: 137
		Reason: OOMKilled
```

Provavelmente, o container está sendo kilado por causa de alta demanda de recursos. Solução é aumentar recursos ou refatorar o código para consumir menos recursos. Tentar primeira opção primeiro. Favor testar demais flows para verificar se o mesmo problema ocorre.

**Comment by mfagundes** [comment]
O particionamento da tabela está sendo feito com 4 `fors` encadeados. Isso costuma ser uma grande fonte de problemas de consumo de recursos.

**Comment by lucascr91** [comment]
@crislanealves

**Comment by laura-l-amaral** [comment]
closed #386
