### ISSUE TITLE
[infra] Mudar schedule para Crontab em flows que rodam em dias específicos do mês

### ISSUE THREAD

**Issue by lucascr91** [basedosdados/pipelines#230]
Forma atual é imprecisa. Ver exemplo em: https://github.com/basedosdados/pipelines/blob/21f90fe687b307b1c06e8d48332e2e28f9894a87/pipelines/datasets/br_poder360_pesquisas/schedules.py

Lista de pipelines a atualizar:

- [x] IGP
- [x] PNADC
- [x] IPCA
- [x] INPC
- [x] IPCA-15
- [x] CGU
- [ ] Diese
- [ ] Comex

Incluir adjustment e filter para não rodar no fim de semana. Ver exemplo:
```python
schedule_municipio_exportacao = Schedule(
    clocks=[
        IntervalClock(
            interval=timedelta(days=30),
            start_date=datetime(1997, 1, 1, 14, 32),  ## confirmar aqui
            labels=[
                constants.BASEDOSDADOS_PROD_AGENT_LABEL.value,
            ],
            parameter_defaults={
                "dataset_id": "br_me_comex_stat",
                "table_id": "municipio_exportacao",
                "materialization_mode": "prod",
                "materialize after dump": True,
                "dbt_alias": False,
            },
        )
    ],
    filters=[filters.is_weekday],
    adjustments=[adjustments.next_weekday],
)
```

**Comment by mfagundes** [comment]
- [ ] igp-di mes (dia 8 de cada mês)
- [ ] igp-di-ano (dia 8 de janeiro de cada ano)
- [ ] igp-m-mes (dia 1 de cada mês)
- [ ] igp-m-ano (dia 1 de janeiro de cada ano)
- [ ] igp-og-mes (de fato, é um índice sem importância, criado apenas por questões políticas) - dia 8 de cada mês
- [ ] igp-og-ano (idem acima) - dia 8 de janeiro de cada ano
- [ ] igp-10-mes (dia 18 de cada mês)
- [ ] pnadc (dia 15 de janeiro de cada ano)

**Comment by mfagundes** [comment]
PNADC alterada em #232

**Comment by mfagundes** [comment]
As flows do Dieese foram desligadas, pois o instituto não fornece os dados gratuitamente. Quanto ao Comex, já é parte de uma nova pipeline que está sendo desenvolvida pela @crislanealves. Assim, vou fechar essa issue e os schedules se integram às pipelines.

**Comment by mfagundes** [comment]
Fechando a issue, uma vez que as que faltam (Dieese e Comex) já estão sendo abordadas em outras issues, pois têm suas particularidades.
