### ISSUE TITLE
[bug-pipelines] br_sp_saopaulo_dieese_icv.mes

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/pipelines#260]
aparentemente os dados dessa tabela não estão sendo atualizados pela pipeline apesar de estar alterando a data de atualização 
<img width="601" alt="image" src="https://user-images.githubusercontent.com/100051996/208199878-dbc5628f-e8c9-4ad7-82f9-04d1316cf6be.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/100051996/208199959-88b880fc-7324-4ccc-bbca-cf88f4a29d09.png">

**Comment by mfagundes** [comment]
Os dados do Dieese estão vindo do `ipeadatapy`. Chequei agora e a última atualização é de setembro de 2018. Na página do [ICV-Dieese](https://www.dieese.org.br/analiseicv/notaBancoDadosIcv.html), inclusive, tem essa nota: 

> A partir de abril de 2018, as variações mensais do ICV por grupo, subgrupo e item não estarão mais disponíveis para consulta pública. Para ter acesso aos dados, será necessária assinatura anual dos produtos e serviços do DIEESE.

Abaixo, consulta feita diretamente no Ipeadata em 17/12/2022.

![image](https://user-images.githubusercontent.com/140761/208249913-6c79319f-9064-4a74-a143-e55b8be531e4.png)

**Comment by laura-l-amaral** [comment]
Hmm, esse aviso, se refere ao _ICV por grupo, subgrupo e item_ e a tabela que temos no BQ não tem essas quebras. Os dados sem quebras também não é mais disponibilizado gratuitamente?

gostaria de esperar a resposta da @crislanealves antes de fechar a issue pq como foi ela que construiu a pipeline, talvez ela tenha mais informações de contexto.

Se esses dados não forem mais atualizar mesmo, podemos desligar a pipeline né?

**Comment by crislanealves** [comment]
Acho que é isso que o @mfagundes explicou. Esses dados já estavam BQ, foi uma pipeline teste.
