### ISSUE TITLE
[bug] Verificar pipeline br_sp_saopaulo_dieese_icv.mes

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/pipelines#266]
No dia 22/12/2022 a pipeline retornou erro no `update_metadata`. Verificar:
- [x] Metadados no CKAN
- [x] Materialização das tabelas
- [x] Versões antigas de pipelines ainda rodando

**Comment by mfagundes** [comment]
1. Verifiquei que não existiam metadados para as tabelas do Dieese, apesar de o dataset existir no CKAN.
2. Chequei no BigQuery e vi que as tabelas materializadas em `prod` estavam lá.
3. No Prefect, observei que a Flow que estava rodando era uma versão antiga (45). Excluí essa versão e rodei a versão mais recente (82).

Após rodar normalmente, inclusive a task `update_metadata`, confirmei que a tabela `mes` aparecia no site. Ativei o schedule da versão mais recente, que irá rodar mensalmente. Quanto à tabela `ano` não existe pipeline para ela.

@laura-l-amaral e @crislanealves peço que verifiquem a necessidade deste conjunto e, caso ele permaneça, fazermos pipelines para todas as tabelas.

**Comment by laura-l-amaral** [comment]
@mfagundes acho que a pipeline antiga que estava ligada limpou os metadados do ckan pq eu subi eles corrigidos na semana passada. Acabei de subir de novo, obrigada pelo aviso ;)
