### ISSUE TITLE
[pipeline] criar operador dummy para skippar 

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/pipelines#278]
Criar operador para skippar quando não houver dados na origem.

**Comment by mfagundes** [comment]
Cris, você pode refinar melhor a sua ideia? Me agrada bastante.

**Comment by crislanealves** [comment]
@mfagundes 

https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/sensors/gcs/index.html

**Comment by laura-l-amaral** [comment]
já implementamos isso com a task check for updates dentro das pipelines
