### ISSUE TITLE
[dados] br_ans_beneficiarios

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/pipelines#348]
**Metadados da base**

1. Descrição: <descrição da base e suas tabelas>

2. Qual o nome do conjunto?  `br_ans_beneficiarios`

3. Qual o nome da(s) tabela(s)?

4. Fonte original dos dados
    * Endereços
        * https://www.gov.br/ans/pt-br/acesso-a-informacao/perfil-do-setor/dados-e-indicadores-do-setor
        * https://dadosabertos.ans.gov.br/FTP/Base_de_dados/Microdados/dados_dbc/
        * https://www.gov.br/ans/pt-br/acesso-a-informacao/perfil-do-setor/dados-e-indicadores-do-setor/baixar-base-de-dados
    * Tem API? `false`
    * É grátis? `true`
    * Cobertura espacial: `sa_br`
    * Cobertura temporal:
    * Frequência de atualização: `quarter`, `month`

5. Raspagem
    * Nível de dificuldade: `medium`
    * Existe código semi-pronto? `false`
    * Dificuldades de big data (alta frequência, alto volume)? `false`

**Comment by arthurfg** [comment]
O qua falta fazer:

- [ ] Testar na Cloud.
- [ ] Criar Schedule.
- [ ] Criar lógica para upload dos dados _retroativos_ atualizados.
