### ISSUE TITLE
Verificar situação da tabela do `br_rj_isp_estatisticas_seguranca`

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/pipelines#352]
- [x] armas_apreendidas_mensal
- [x] evolucao_mensal_cisp
- [x] evolucao_mensal_municipio
- [x] evolucao_mensal_uf
- [x] evolucao_policial_morto_servico_mensal
- [x] feminicipio_mensal_cisp
- [x] taxa_evolucao_mensal_municipio
- [x] taxa_evolucao_mensal_uf

**Comment by tricktx** [comment]
O problema da pipeline era o `dbt alias`, já foi ajustado em dev: 

* Próximos passos: Materializar novamente tudo em prod após finalizar por completo a pipeline da anatel.
