### ISSUE TITLE
[fix] br_mercadolivre_ofertas

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/pipelines#359]
Coleta: 
- [x] Melhorar o preenchimento da coluna de preço e categoria (aumentar a quantidade de try)
- [x] Arrumar dados no BQ aparecendo null quando existe informação de preço
- [x] Preço final igual ao preço origem
- [x] Arrumar os parâmetros do schedule

Arquitetura/DBT item 
- [x] Coluna data_hora quebrar em uma coluna data e outra hora
- [x] Renomear a coluna dia que só existe no BQ para data e adicionar a arquitetura
- [x] Item_id no BQ e na arquitetura id_item
- [x] Reordenação das colunas
- [x] Coluna preco_final com dados NaN ao invés de Null
- [x] Deletar dados nulos em preco_final e preco_final
- [x] Cruzar nome do vendedor com o da tabela `vendedor` para obter o ID
- [x] Coluna caracteristicas como json (manteve)
- [x] Teste do modelo DBT em dev

Arquitetura/DBT vendedor 
- [x] Vendedor_id no BQ e na arquitetura id_vendedor
- [x] Dia no BQ e na arquitetura data_consulta
- [x] Reordenação das colunas
- [x] Quebrar a coluna opinioes
- [x] Coluna id_vendedor com dados duplicados
- [x] Dados duplicados com mudanças na opiniões
- [x] Teste do modelo DBT em dev
- [x] Arrumar questão de duplicatas

Metadado: 
- [x] Remover colunas duplicadas
- [x] Ajustar o schema conforme mudanças na arquitetura
- [x] Corrigir metadados geral (nome do conjunto, imagem do conjunto, etc 
- [x] Incluir update_metadata

Pipeline:
- [x] incluir update_temporal_coverage

Bloqueios:

- [x] Teste: coleta dos preços de forma assíncrona e sem ser assíncrona (sem decorador)
- [x] Teste: acrescentar classes
- [x] Buscar entender se existe mais recursos no ambiente de dev do que em prod

**Comment by laura-l-amaral** [comment]
Próximos Passos

- [ ] testar usar o selenium
- [ ] testar puxar todas as páginas

**Comment by gabrielle-carv** [comment]
- [ ] mudar a `class_` para colunas de categoria_principal, outras_categorias , caracteristicas, envio_nacional

**Comment by gabrielle-carv** [comment]
- [ ]  levar dados históricos para `br_mercadolivre_ofertas_historico` e apagar em `br_mercadolivre_ofertas`
