### ISSUE TITLE
[captura] Subir dados do Twitter

### ISSUE THREAD

**Issue by fernandascovino** [basedosdados/pipelines#4]
Não sei como tão organizando aqui ainda, mas quero subir esses dados de analytics :)

**Comment by vncsna** [comment]
@fernandascovino o que é necessário fazer em específico?

**Comment by fernandascovino** [comment]
subir os dados da API do twitter para criar nosso painel de redes sociais, ja tenho o codigo para isso

ia fazer hoje mas vi que o repo ainda ta sendo estruturado... @basedosdados/infra quando tiver ok para criar essa pipeline avisem por favor e a gente da uma azeitada na documentação

**Comment by lucascr91** [comment]
base está em produção. Porém, é necessário migrar o conteúdo do dataset para `br_bd_indicadores`. Ver https://github.com/basedosdados/pipelines/issues/68
