### ISSUE TITLE
[fix] br_cvm_fi

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/pipelines#400]

**Comment by arthurfg** [comment]
- o problema na `documentos_balancete` era que as colunas de partição estavam como int, mas o to_partitions transforma em str e filtra baseado na string, por isso estava retornando partições vazias.
- na tabela de `informacao_cadastral` o erro era por conta do coverage que tinha sido apagado, devo ter feito isso sem querer ao testar. Já corrigi, não havia afetado a materialização.
- to recebendo um erro de `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 2402: invalid continuation byte` na tabela `perfil_mensal`, isso é problema do pandas, que por algum motivo não consegue ler o arquivo bem. Já vou resolver.

O que estou fazendo:

- [ ] Usar a função do R para ler o csv dentro do python.
- [ ] Testar local.
- [ ] Testar na cloud.
- [ ] Mergear PR.
