### ISSUE TITLE
[dados] br_denatran_frota

### ISSUE THREAD

**Issue by folhesgabriel** [basedosdados/pipelines#415]
#334

Tarefas:
- [x] Fazer alteração para particionar os dados
- [x] Subir os dados históricos pra dev
  - [x] municipio
  - [x] uf
- [x] Fazer o modelo dbt e o schema 
- [x] Materializar os dados em basedosdados-dev
- [x] Fazer testes
- [x] Preencher metadados
- [x] Testar versão final do flow na cloud

- 01/12/2023: bloqueio -> tabela de municipio_tipo teve dados do diretório de município (ddd, ids...) pivotados como valores da coluna tipo_veiculo; Aguardar correção para prosseguir

**Comment by laura-l-amaral** [comment]
- [ ] corrigir valores de veiculos no modelo_dbt + permissionamento (pisa)
- [ ] ajustar update_django_metadata parciamente fechado
- [ ] arrumar check_for_updates (tamir)

**Comment by laura-l-amaral** [comment]
- [ ] incluir 10 meses faltantes da tabela de uf
- [ ] mudar para o flow nao quebrar quando não tiver atualização

**Comment by uiro-bi** [comment]
> * [ ]  incluir 10 meses faltantes da tabela de uf
> * [ ]  mudar para o flow nao quebrar quando não tiver atualização

- [ ] Rodar  a pipeline para os anos de 2022; 2015; 2003; 2004 para tabela `uf_tipo`;
- [ ] Retirar partições de sigla_uf para `ambas tabelas`
- [ ] Carregar dados históricos corrigidos em .parquet das tabelas `uf_tipo `e `municipio_tipo`;
- [ ] Corrigir partições e clusterização DBT;
- [ ] Materializar dados em dev e rodar test;
- [ ] Rodar pipelines em prod;
- [ ] Apagar schemas em prod, rodar table approve e apagar metadados antigos;

**Comment by folhesgabriel** [comment]
> * [ ]  incluir 10 meses faltantes da tabela de uf
> * [ ]  mudar para o flow nao quebrar quando não tiver atualização

- [x] Rodar  a pipeline para os anos de 2022; 2015; 2003; 2004 para tabela `uf_tipo`;
- [x] Retirar partições de sigla_uf para `ambas tabelas`
- [x] Carregar dados históricos corrigidos em .parquet das tabelas `uf_tipo `e `municipio_tipo`;
- [x] Corrigir partições e clusterização DBT;
- [x] Materializar dados em dev e rodar test;
- [x] Rodar pipelines em prod;
- [ ] Apagar schemas em prod, rodar table approve e apagar metadados antigos;
