### ISSUE TITLE
[dados] br_me_cafir

### ISSUE THREAD

**Issue by rdahis** [basedosdados/pipelines#447]
**Metadados da base**

1. Descrição: <descrição da base e suas tabelas>

2. Qual o nome do conjunto? `br_me_cafir`

3. Qual o nome da(s) tabela(s)? `microdados`

4. Fonte original dos dados: https://dados.gov.br/dados/conjuntos-dados/cadastro-de-imoveis-rurais-cafir

5. Cobertura espacial: Brasil

6. Cobertura temporal: de XXXX a YYYY

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template
- [x] Preencher as tabelas de arquitetura
- [x] Escrever código de captura e limpeza de dados.
- [x] Organizar arquivos auxiliares, se necessário.
- [ ] Criar tabela dicionário, se necessário.
- [ ] Subir arquiteturas, dados e arquivos auxiliares no Google Cloud.
- [ ] Enviar tudo para revisão.

**Comment by laura-l-amaral** [comment]
- [ ] puxar o id_municipio
- [ ] coluna que está fora do dicionario
- [ ] entendendo a coluna de area
