### ISSUE TITLE
[dados-pipeline] br_stf_corte_aberta

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/pipelines#473]
Links úteis: https://portal.stf.jus.br/textos/verTexto.asp?servico=estatistica&pagina=explicafases#:~:text=As%20decisões%20podem%20ser%20monocráticas,e%20decisões%20em%20recurso%20interno.

https://portal.stf.jus.br/jurisprudencia/glossario.asp

**Comment by tricktx** [comment]
- [ ] Arquitetura decisões (Lista de processos) - Pipeline
     - [ ] Tratamento dos dados
     - [ ] Modelo dbt
     - [ ] Flows
     - [ ] Tasks
     - [ ] Testar local
     - [ ] Testar Cloud
- [ ] Arquitetura (Lista das partes) - Apenas subida dos dados
     - [ ] Tratamento dos dados
     - [ ] Modelo dbt
     - [ ] Subida dos dados
