### ISSUE TITLE
[dados] br_ons_

### ISSUE THREAD

**Issue by folhesgabriel** [basedosdados/pipelines#510]
- Modifica em todas as pipelines da ons:
  -  task de download de dados para sempre baixar o arquivo mais recente
      - cria função parse_year_or_year_month para identificar arquivo mais recente que deve ser 
          baixado.
  - Criar task extract_last_date_from_bq para extrair data mais recente das tabelas no bigquery
  - Criar função extrai_data_recente para extrair data mais recente do arquivo mais recente baixado e comparar com a data no BQ
  - Insere todas as modificações pertinentes nos Flows 
  
- A pipeline de `restricao_operacao_usinas_eolicas` sera incluida no conjunto `br_ons_avaliacao_operacao`
- A pipeline de `custo_variavel_unitario_usinas_termicas` será incluida no conjunto `br_ons_estimativas_custos`

1. **Arquiteturas** 

- [x] `restricao_operacao_usinas_eolicas `
- [x] `custo_variavel_unitario_usinas_termicas`

2. **Pipeline de captura de dados**

- [x] `restricao_operacao_usinas_eolicas `
- [x] `custo_variavel_unitario_usinas_termicas`

3. **Modelos DBT e Schema** 

- [x] `restricao_operacao_usinas_eolicas `
- [x] `custo_variavel_unitario_usinas_termicas`

4. **Preenchimento de metadados** 

- [x] `restricao_operacao_usinas_eolicas `
- [x] `custo_variavel_unitario_usinas_termicas`

**Comment by laura-l-amaral** [comment]
Tarefas pós data check
1. geracao_usina - verificar duplicação ao longo dos meses
2. operacao_usinas_eolicas - verificar restricao mes 10 de 23
3. energia natural afluente - checar se as duplicações vem da fonte original

**Comment by laura-l-amaral** [comment]
- [ ] Corrigir metadado de nível de observação
