### ISSUE TITLE
[dados] br_cgu_beneficios_cidadao

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/pipelines#521]

**Comment by arthurfg** [comment]
- [ ] Scrapper para extrair a data de atualização.
- [ ] Criar lógica para atualização.
- [ ] Estrutura de download dos arquivos.
- [ ] Criar modelo dbt.
- [ ] Subir dados históricos.
- [ ] Escrever os testes.
- [ ] Fechar PR.
