### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by gabrielle-carv** [basedosdados/pipelines#533]
- [x] mundo_transfermarkt_competicoes.brasileirao_serie_a
- [x] mundo_transfermarkt_competicoes.copa_brasil
- [x] mundo_transfermarkt_competicoes_internacionais.champions_leage
- [x] br_me_cnpj.empresas
- [x] br_me_cnpj.estabelecimentos
- [x] br_me_cnpj.socios
- [x] br_me_cnpj.simples

**Comment by laura-l-amaral** [comment]
- [ ] mercado_livre
