### ISSUE TITLE
br_camara_dados_abertos

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/pipelines#648]
- [ ]  Frentes (2 tabelas)
- [ ] Eventos (4 tabelas)
- [ ] Funcionários (1 tabelas)

---------------------

- [x] Arquitetura
- [x] Subida dos dados para o storage
- [x] Modelo dbt em dev
- [ ] Construção da util.py e task.py
- [ ] Modelo dbt em staging
- [ ] metadados

**Comment by tricktx** [comment]
Tabelas de evento e frente_deputado vieram da fonte com . no nome da coluna, logo, o BigQuery não aceitou. 

- Tive que renomear (substitui os . por _) para o BQ aceitar e eu nomear posteriormente tudo pelo dbt, dessa forma, mantendo o padrão das outras tabelas.
