### ISSUE TITLE
Ao materializar uma tabela em produção rodar os testes

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/pipelines#682]

**Comment by arthurfg** [comment]
Tabelas com testes:

- [ ] `br_bcb_agencia__agencia`
- [ ] `br_bcb_estban__municipio`
- [ ] `br_bcb_estban__agencia`
- [ ] `br_bcb_taxa_cambio`
- [ ] `br_bd_diretorios_brasil__cnae_1`
- [ ] `br_bd_diretorios_brasil__cnae_2`
- [ ] `br_bd_metadados__prefect_flows`
- [ ] `br_bd_metadados__prefect_flow_runs`
- [ ] `br_camara_dados_abertos`
- [ ] `br_cgu_beneficios_cidadao__novo_bolsa_familia`
- [ ] `br_cgu_beneficios_cidadao__garantia_safra`
- [ ] `br_cgu_beneficios_cidadao__bpc`
- [ ] `br_cnj_improbidade_administrativa__condenacao`
- [ ] `br_cvm_fi__documentos_balancete`
- [ ] `br_datahackers_state_data__microdados`
- [ ] `br_denatran_frota__municipio_tipo`
- [ ] `br_firjan_ifgf__ranking`
- [ ] `br_ibge_censo_2022`
- [ ] `br_ibge_pevs__producao_extracao_vegetal`
- [ ] `br_ibge_pevs__producao_silvicultura`
- [ ] `br_ibge_pib__municipio`
- [ ] `br_ibge_pib__gini`
- [ ] `br_ibge_pnadc__educacao`
- [ ] `br_inep_censo_escolar__escola`
- [ ] `br_inep_indicadores_educacionais__municipio`
- [ ] `br_inpe_prodes__municipio_bioma`
- [ ] `br_inpe_queimadas__microdados`
- [ ] `br_inpe_sisam__microdados`
- [ ] `br_me_caged__microdados_movimentacao`
- [ ] `br_me_caged_microdados_movimentacao_fora_prazo`
- [ ] `br_me_caged_microdados_movimentacao_excluida`
- [ ] `br_me_cnpj__empresas`
- [ ] `br_me_cnpj__socios`
- [ ] `br_me_cnpj__estabelecimentos`
- [ ] `br_ms_cnes`
- [ ] `br_ms_sinasc__microdados`
- [ ] `br_ons_avaliacao_operacao`
- [ ] `br_ons_estimativa_custos`
- [ ] `br_trase_supply_chain`
- [ ] `mundo_transfermarkt_competicoes_internacionais__champions_league`
- [ ] `world_oceanos_mapeamento__mapeamento`
- [ ] `world_oecd_public_finance__country`
