### ISSUE TITLE
br_anatel

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/pipelines#697]
- [x] Desativar a pipeline
- [x] Consertar pipeline
- [x] Refatorar código banda larga
- [x] Refatorar código telefonia móvel
- [x] Testes

**Comment by tricktx** [comment]
## O erro de requisição no site da Anatel continua. 
* Uma requisição simples com um headers me retorna 403, na maioria das vezes, mas por incrível que pareça, rodei uma vez e os dados foram baixados. 
```
headers = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.93 Safari/537.36",
}
http_response = requests.get("https://www.anatel.gov.br/dadosabertos/paineis_de_dados/acessos/acessos_banda_larga_fixa.zip", headers=headers)
```

* O Pedro conseguiu retirar o espelho de 0% da tela inicial do site (segue o print abaixo). Entretanto, quando seguimos o caminho para baixar os dados via selenium, aparece uma mensagem de erro:

```
import requests
import time
from selenium.webdriver.common.by import By
from selenium import webdriver

driver = webdriver.Chrome()
driver.get("https://informacoes.anatel.gov.br/paineis/acessos")
time.sleep(15)
driver.execute_script(
    "document.evaluate('//*[@id=\"main-navigation\"]/div[4]', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.style.display = 'none';"
)
time.sleep(15)
driver.find_element(By.XPATH, '//*[@id="menu-contexto"]/ul/li[1]/a').click()
time.sleep(15)
driver.find_element(By.XPATH, '//*[@id="menu-contexto"]/ul/li[1]/ul/li[1]/a').click()
```

Espelho:  ![Image](https://github.com/basedosdados/pipelines/assets/105399231/0a47e610-3f08-42b1-af1e-e0400ad4abf7)

Mensagem de erro ao clicar no link para baixar os dados: 

![Image](https://github.com/basedosdados/pipelines/assets/105399231/af28408f-52a7-4c39-a56b-e5370ca43b7b)

**Comment by laura-l-amaral** [comment]
@tricktx qual o resultado qunado vc tenta fazer o download dos dados?

**Comment by tricktx** [comment]
@laura-l-amaral quando eu tento rodar o seguinte código: 


![Image](https://github.com/basedosdados/pipelines/assets/105399231/47ddcf01-2f34-4c90-948c-3a44ed0be024)

Ele me retornar: 


![Image](https://github.com/basedosdados/pipelines/assets/105399231/57cae494-b7c3-4f45-b2f4-5c916a11856c)
